# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "nokogiri", "~> 1.10"
gem "httparty", "~> 0.17.1"

gem "byebug", "~> 11.0", :groups => [:development, :text]
gem "pry", "~> 0.12.2", :groups => [:development, :text]

gem "rest-client", "~> 2.1"

gem "rubocop", "~> 0.76.0", :groups => [:development, :test]
